<?php

namespace mmaurice\api\tinkoff\invest\types;

class OperationTypeWithCommissionType extends \mmaurice\apigate\types\EnumType
{
    const OPERATION_TYPE_WITH_COMISSION_TYPE_BUY = 'Buy';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_BUY_CARD = 'BuyCard';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_SELL = 'Sell';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_BROKER_COMISSION = 'BrokerCommission';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_EXCHANGE_COMISSION = 'ExchangeCommission';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_SERVICE_COMISSION = 'ServiceCommission';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_MARGIN_COMISSION = 'MarginCommission';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_OTHER_COMISSTION = 'OtherCommission';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_PAY_IN = 'PayIn';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_PAY_OUT = 'PayOut';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_TAX = 'Tax';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_TAX_LUCRE = 'TaxLucre';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_TAX_DIVIDEND = 'TaxDividend';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_TAX_COUPON = 'TaxCoupon';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_TAX_BACK = 'TaxBack';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_REPAYMENT = 'Repayment';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_PART_REPAYMENT = 'PartRepayment';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_COUPON = 'Coupon';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_DIVIDEND = 'Dividend';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_SECURITY_IN = 'SecurityIn';
    const OPERATION_TYPE_WITH_COMISSION_TYPE_SECURITY_OUT = 'SecurityOut';

    protected $options = [
        'enum' => [
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_BUY,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_BUY_CARD,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_SELL,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_BROKER_COMISSION,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_EXCHANGE_COMISSION,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_SERVICE_COMISSION,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_MARGIN_COMISSION,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_OTHER_COMISSTION,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_PAY_IN,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_PAY_OUT,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_TAX,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_TAX_LUCRE,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_TAX_DIVIDEND,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_TAX_COUPON,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_TAX_BACK,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_REPAYMENT,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_PART_REPAYMENT,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_COUPON,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_DIVIDEND,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_SECURITY_IN,
            self::OPERATION_TYPE_WITH_COMISSION_TYPE_SECURITY_OUT,
        ],
    ];
}
